In [1]:
import torch
from torch_geometric.data import Data

/home/dominik/miniconda3/envs/relationalgnn/lib/python3.14/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: Could not load this library: /home/dominik/miniconda3/envs/relationalgnn/lib/python3.14/site-packages/libpyg.so
  import torch_geometric.typing
/home/dominik/miniconda3/envs/relationalgnn/lib/python3.14/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: Could not load this library: /home/dominik/miniconda3/envs/relationalgnn/lib/python3.14/site-packages/libpyg.so
  import torch_geometric.typing
/home/dominik/miniconda3/envs/relationalgnn/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [25]:
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
edge_index = edge_index.t().contiguous()
edge_index

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [26]:
row, col = edge_index

In [27]:
row

tensor([0, 1, 1, 2])

In [28]:
col

tensor([1, 0, 2, 1])

In [29]:
from torch_geometric.utils import degree

In [30]:
deg = degree(row, 3, dtype=torch.long)
print(deg)
deg_inv_sqrt = deg.pow(-0.5)
deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
deg_inv_sqrt

tensor([1, 2, 1])


tensor([1.0000, 0.7071, 1.0000])

In [34]:
norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
norm.shape

torch.Size([4])

In [39]:
norm.view(-1, 1)

tensor([[0.7071],
        [0.7071],
        [0.7071],
        [0.7071]])

In [37]:
x_j = torch.arange(0, 3*4, dtype=torch.float).view(4, 3)
x_j

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [38]:
norm.view(-1, 1) * x_j

tensor([[0.0000, 0.7071, 1.4142],
        [2.1213, 2.8284, 3.5355],
        [4.2426, 4.9497, 5.6569],
        [6.3640, 7.0711, 7.7782]])